export const appRoutes = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  user: '/user',
  // Vendor Kitchen Platform
  recipe: '/recipe',
  recipeForm: '/recipe/add',
  weeklyMenu: '/weekly-menu',
  weeklyMenuForm: '/weekly-menu/add',
  category: '/category',
  ingredient: '/ingredient',
  dishtype: '/dishtype',
  cuisine: '/cuisine',
  packagingMaterial: '/packaging-material',
  variant: '/variant',
  variantForm: '/variant/add',
  allergens: '/allergens',
  barcodePlace: '/barcode-place',
  vendorDashboard: '/vendor-dashboard',
  productionReportSummary: '/reports/production-summary',
  productionReportList: '/reports/production-list',
  recipeRatings: '/recipe-ratings',
}
