#!/bin/sh
echo "Running pre-commit checks..."

# 1. Build
echo "Building project..."
npm run build
if [ $? -ne 0 ]; then
 echo "Build failed! Commit aborted."
 exit 1
fi

# 2. Test
echo "Running tests..."
npm run test
if [ $? -ne 0 ]; then
 echo "Tests failed! Commit aborted."
 exit 1
fi

# 3. Lint
echo "Running linter..."
npm run lint
if [ $? -ne 0 ]; then
 echo "Linting failed! Commit aborted."
 exit 1
fi



echo "All checks passed!"
